"""Mini Dungeon - Dungeon Card Generation"""

import random
from constants import (
    CARD_COLS, CARD_ROWS, TILE_ROAD, TILE_WALL, TILE_DOOR,
    TILE_DOOR_LOCKED, TILE_CHEST, MONSTERS, BOSS_CARD_THRESHOLD,
    BOSS_GRID_ROWS, BOSS_GRID_COLS
)


class DungeonCard:
    """A 5x7 dungeon card with tiles, monsters, and items."""

    def __init__(self, card_id, is_boss=False):
        self.card_id = card_id
        self.is_boss = is_boss
        self.is_first = (card_id == 1)
        self.is_boss_sub = False  # Set True for boss room sub-cards
        self.tiles = [[TILE_WALL] * CARD_COLS for _ in range(CARD_ROWS)]
        self.monsters = []  # list of (row, col, monster_type)
        self.chests = []  # list of (row, col)
        self._generate()

    def _generate(self):
        """Generate dungeon card layout."""
        if self.is_boss:
            self._generate_boss_room()
        else:
            self._generate_normal()

    def _generate_normal(self):
        """Generate a normal dungeon card with paths, monsters, chests, doors."""
        # Ensure center of each edge is road (connection points)
        # Top edge center: (0, 5)
        # Bottom edge center: (6, 5)
        # Left edge center: (3, 0)
        # Right edge center: (3, 10)

        # Start by carving paths from each edge connection point
        connection_points = [
            (0, CARD_COLS // 2),   # top
            (CARD_ROWS - 1, CARD_COLS // 2),  # bottom
            (CARD_ROWS // 2, 0),   # left
            (CARD_ROWS // 2, CARD_COLS - 1),  # right
        ]

        # Make connection points road
        for r, c in connection_points:
            self.tiles[r][c] = TILE_ROAD

        # Generate paths connecting all connection points through center area
        center_r, center_c = CARD_ROWS // 2, CARD_COLS // 2
        self.tiles[center_r][center_c] = TILE_ROAD

        # Carve paths from each connection to center
        for r, c in connection_points:
            self._carve_path(r, c, center_r, center_c)

        # Add some random rooms/corridors
        num_rooms = random.randint(1, 2)
        for _ in range(num_rooms):
            room_r = random.randint(1, CARD_ROWS - 2)
            room_c = random.randint(1, CARD_COLS - 2)
            room_w = random.randint(2, 3)
            room_h = random.randint(2, 3)
            self._carve_room(room_r, room_c, room_w, room_h)
            # Connect room to center
            self._carve_path(room_r, room_c, center_r, center_c)

        # Add random extra corridors for variety
        for _ in range(random.randint(1, 3)):
            r1 = random.randint(1, CARD_ROWS - 2)
            c1 = random.randint(1, CARD_COLS - 2)
            r2 = random.randint(1, CARD_ROWS - 2)
            c2 = random.randint(1, CARD_COLS - 2)
            self._carve_path(r1, c1, r2, c2)

        # Place doors (on road tiles that are narrow passages)
        self._place_doors()

        # First card has no monsters or chests — safe starting area
        if self.is_first:
            return

        # Place monsters on road tiles
        self._place_monsters()

        # Place chests on road tiles
        self._place_chests()

    def _generate_boss_room(self):
        """Generate a single sub-card of the boss room.
        The actual boss layout is generated by DungeonDeck.generate_boss_cards().
        This is a fallback that just creates an open room."""
        for r in range(1, CARD_ROWS - 1):
            for c in range(1, CARD_COLS - 1):
                self.tiles[r][c] = TILE_ROAD
        self.tiles[0][CARD_COLS // 2] = TILE_ROAD
        self.tiles[CARD_ROWS - 1][CARD_COLS // 2] = TILE_ROAD
        self.tiles[CARD_ROWS // 2][0] = TILE_ROAD
        self.tiles[CARD_ROWS // 2][CARD_COLS - 1] = TILE_ROAD

    def _carve_path(self, r1, c1, r2, c2):
        """Carve a path between two points (L-shaped)."""
        r, c = r1, c1
        # Move horizontally first, then vertically (or randomly choose)
        if random.random() < 0.5:
            # Horizontal then vertical
            while c != c2:
                c += 1 if c2 > c else -1
                if 0 <= r < CARD_ROWS and 0 <= c < CARD_COLS:
                    if self.tiles[r][c] == TILE_WALL:
                        self.tiles[r][c] = TILE_ROAD
            while r != r2:
                r += 1 if r2 > r else -1
                if 0 <= r < CARD_ROWS and 0 <= c < CARD_COLS:
                    if self.tiles[r][c] == TILE_WALL:
                        self.tiles[r][c] = TILE_ROAD
        else:
            # Vertical then horizontal
            while r != r2:
                r += 1 if r2 > r else -1
                if 0 <= r < CARD_ROWS and 0 <= c < CARD_COLS:
                    if self.tiles[r][c] == TILE_WALL:
                        self.tiles[r][c] = TILE_ROAD
            while c != c2:
                c += 1 if c2 > c else -1
                if 0 <= r < CARD_ROWS and 0 <= c < CARD_COLS:
                    if self.tiles[r][c] == TILE_WALL:
                        self.tiles[r][c] = TILE_ROAD

    def _carve_room(self, start_r, start_c, width, height):
        """Carve a rectangular room."""
        for r in range(start_r, min(start_r + height, CARD_ROWS - 1)):
            for c in range(start_c, min(start_c + width, CARD_COLS - 1)):
                if 0 < r < CARD_ROWS - 1 and 0 < c < CARD_COLS - 1:
                    self.tiles[r][c] = TILE_ROAD

    def _place_doors(self):
        """Place 0-2 doors on narrow passages, never adjacent to each other."""
        door_candidates = []
        for r in range(1, CARD_ROWS - 1):
            for c in range(1, CARD_COLS - 1):
                if self.tiles[r][c] == TILE_ROAD:
                    # Check if it's a narrow passage (walls on 2 opposite sides)
                    h_walls = (self.tiles[r][c-1] == TILE_WALL and
                               self.tiles[r][c+1] == TILE_WALL)
                    v_walls = (self.tiles[r-1][c] == TILE_WALL and
                               self.tiles[r+1][c] == TILE_WALL)
                    if h_walls or v_walls:
                        door_candidates.append((r, c))

        num_doors = min(random.randint(0, 2), len(door_candidates))
        if not door_candidates or num_doors == 0:
            return

        random.shuffle(door_candidates)
        placed = []
        for r, c in door_candidates:
            if len(placed) >= num_doors:
                break
            # Ensure no door within 2 tiles of an already-placed door
            too_close = False
            for pr, pc in placed:
                if abs(r - pr) + abs(c - pc) < 3:
                    too_close = True
                    break
            if too_close:
                continue
            if random.random() < 0.3:
                self.tiles[r][c] = TILE_DOOR_LOCKED
            else:
                self.tiles[r][c] = TILE_DOOR
            placed.append((r, c))

    def _place_monsters(self):
        """Place 1-4 monsters on road tiles."""
        road_tiles = []
        center_r, center_c = CARD_ROWS // 2, CARD_COLS // 2
        for r in range(CARD_ROWS):
            for c in range(CARD_COLS):
                if self.tiles[r][c] == TILE_ROAD:
                    # Don't place on connection points or very center
                    if (r, c) not in [(0, CARD_COLS//2), (CARD_ROWS-1, CARD_COLS//2),
                                      (CARD_ROWS//2, 0), (CARD_ROWS//2, CARD_COLS-1),
                                      (center_r, center_c)]:
                        road_tiles.append((r, c))

        num_monsters = min(random.randint(1, 3), len(road_tiles))
        if road_tiles:
            positions = random.sample(road_tiles, num_monsters)
            for r, c in positions:
                # Weighted selection from all normal monster types
                types =   ["Goblin", "Bat", "Slime", "Spider", "Skeleton", "Orc", "Wraith"]
                weights = [25,       20,    15,      15,       15,         5,     5]
                monster_type = random.choices(types, weights=weights, k=1)[0]
                self.monsters.append((r, c, monster_type))

    def _place_chests(self):
        """Place 0-2 chests on road tiles without monsters."""
        monster_positions = set((r, c) for r, c, _ in self.monsters)
        road_tiles = []
        for r in range(CARD_ROWS):
            for c in range(CARD_COLS):
                if (self.tiles[r][c] == TILE_ROAD and
                        (r, c) not in monster_positions):
                    road_tiles.append((r, c))

        num_chests = min(random.randint(0, 2), len(road_tiles))
        if road_tiles and num_chests > 0:
            positions = random.sample(road_tiles, num_chests)
            for r, c in positions:
                self.tiles[r][c] = TILE_CHEST
                self.chests.append((r, c))


class DungeonDeck:
    """Manages the deck of dungeon cards."""

    def __init__(self):
        self.cards_drawn = 0
        self.boss_drawn = False

    def draw_card(self):
        """Draw the next dungeon card (never draws boss here)."""
        self.cards_drawn += 1
        return DungeonCard(self.cards_drawn)

    def should_draw_boss(self):
        """Check if next expansion should be the boss room."""
        return self.cards_drawn >= BOSS_CARD_THRESHOLD and not self.boss_drawn

    def generate_boss_cards(self, entry_side="top"):
        """Generate boss room as 3x3 grid of standard cards.
        entry_side: which side of the 3x3 block the entrance is on.
        Returns: dict of {(offset_r, offset_c): DungeonCard},
                 entry_door_local (local_r, local_c in the entry card),
                 monsters list of (offset_r, offset_c, local_r, local_c, type)
        """
        self.boss_drawn = True
        self.cards_drawn += 1

        total_rows = BOSS_GRID_ROWS * CARD_ROWS  # 15
        total_cols = BOSS_GRID_COLS * CARD_COLS   # 21

        # Build full boss room tile grid
        grid = [[TILE_WALL] * total_cols for _ in range(total_rows)]

        # Carve the main arena (leave 1-tile wall border)
        for r in range(1, total_rows - 1):
            for c in range(1, total_cols - 1):
                grid[r][c] = TILE_ROAD

        # --- Complex layout features ---

        # 4 stone pillars (2x2 wall blocks) for cover
        pillar_positions = [
            (4, 6), (4, 13),   # upper pillars
            (10, 6), (10, 13),  # lower pillars
        ]
        for pr, pc in pillar_positions:
            for dr in range(2):
                for dc in range(2):
                    if 0 <= pr + dr < total_rows and 0 <= pc + dc < total_cols:
                        grid[pr + dr][pc + dc] = TILE_WALL

        # Corner alcoves (small rooms with chests)
        alcoves = [
            (1, 1, 3, 3),      # top-left
            (1, 17, 3, 3),     # top-right
            (11, 1, 3, 3),     # bottom-left
            (11, 17, 3, 3),    # bottom-right
        ]
        chest_positions = []
        for ar, ac, ah, aw in alcoves:
            # Partial wall around alcove (leave opening)
            for c in range(ac, ac + aw):
                if 0 <= ar + ah < total_rows and 0 <= c < total_cols:
                    grid[ar + ah][c] = TILE_WALL  # bottom/top wall of alcove
            for r in range(ar, ar + ah):
                edge_c = ac + aw if ac < total_cols // 2 else ac - 1
                if 0 <= r < total_rows and 0 <= edge_c < total_cols:
                    grid[r][edge_c] = TILE_WALL
            # Opening in the wall
            open_r = ar + ah // 2
            open_c = ac + aw if ac < total_cols // 2 else ac - 1
            if 0 <= open_r < total_rows and 0 <= open_c < total_cols:
                grid[open_r][open_c] = TILE_ROAD
            # Chest inside
            chest_r = ar + 1
            chest_c = ac + 1
            if 0 <= chest_r < total_rows and 0 <= chest_c < total_cols:
                grid[chest_r][chest_c] = TILE_CHEST
                chest_positions.append((chest_r, chest_c))

        # Center raised area border (ring of different floor around boss)
        center_r, center_c = total_rows // 2, total_cols // 2
        for dr in range(-3, 4):
            for dc in range(-4, 5):
                r, c = center_r + dr, center_c + dc
                if (abs(dr) == 3 or abs(dc) == 4) and 0 <= r < total_rows and 0 <= c < total_cols:
                    if grid[r][c] == TILE_ROAD:
                        # Leave openings at cardinal directions
                        if not (dr == 0 or dc == 0):
                            grid[r][c] = TILE_WALL

        # Side corridors (narrow paths along edges for kiting)
        # Already open from the main carve, but add wall bumps for cover
        wall_bumps = [(3, 1), (7, 1), (11, 1),
                      (3, total_cols - 2), (7, total_cols - 2), (11, total_cols - 2)]
        for br, bc in wall_bumps:
            if 0 <= br < total_rows and 0 <= bc < total_cols:
                grid[br][bc] = TILE_WALL

        # --- Entry door ---
        door_r, door_c = 0, 0
        if entry_side == "top":
            door_r, door_c = 0, total_cols // 2
        elif entry_side == "bottom":
            door_r, door_c = total_rows - 1, total_cols // 2
        elif entry_side == "left":
            door_r, door_c = total_rows // 2, 0
        elif entry_side == "right":
            door_r, door_c = total_rows // 2, total_cols - 1
        grid[door_r][door_c] = TILE_DOOR

        # --- Slice into 3x3 standard cards ---
        cards = {}
        for gr in range(BOSS_GRID_ROWS):
            for gc in range(BOSS_GRID_COLS):
                card = DungeonCard.__new__(DungeonCard)
                card.card_id = self.cards_drawn
                card.is_boss = True
                card.is_first = False
                card.is_boss_sub = True  # Prevent expansion
                card.monsters = []
                card.chests = []
                card.tiles = []
                for lr in range(CARD_ROWS):
                    row = []
                    for lc in range(CARD_COLS):
                        row.append(grid[gr * CARD_ROWS + lr][gc * CARD_COLS + lc])
                    card.tiles.append(row)
                # Track chests
                for cr, cc in chest_positions:
                    clr = cr - gr * CARD_ROWS
                    clc = cc - gc * CARD_COLS
                    if 0 <= clr < CARD_ROWS and 0 <= clc < CARD_COLS:
                        card.chests.append((clr, clc))
                cards[(gr, gc)] = card

        # Monsters (placed in world-relative coords, converted to card-local)
        boss_r = center_r - 1  # 2x2 boss top-left
        boss_c = center_c - 1
        monsters = [(boss_r, boss_c, "Boss")]
        # Guard monsters in the arena
        guard_positions = [
            (3, 9), (3, 11),     # upper mid
            (11, 9), (11, 11),   # lower mid
            (7, 4), (7, 16),     # side guards
        ]
        for gr_pos, gc_pos in guard_positions:
            mtype = random.choice(["Skeleton", "Orc", "Wraith", "Spider"])
            monsters.append((gr_pos, gc_pos, mtype))

        # Convert monster positions to card-local
        for mr, mc, mtype in monsters:
            card_gr = mr // CARD_ROWS
            card_gc = mc // CARD_COLS
            local_r = mr % CARD_ROWS
            local_c = mc % CARD_COLS
            if (card_gr, card_gc) in cards:
                cards[(card_gr, card_gc)].monsters.append((local_r, local_c, mtype))

        # Entry door info (which card and local position)
        door_card_gr = door_r // CARD_ROWS
        door_card_gc = door_c // CARD_COLS
        door_local_r = door_r % CARD_ROWS
        door_local_c = door_c % CARD_COLS

        return cards, (door_card_gr, door_card_gc, door_local_r, door_local_c)
